### PR TITLE
Use ipv4 filter instead of json query

### PR DESCRIPTION
**Pull request by cwilkers**
https://github.com/oVirt/ovirt-ansible-vm-infra/issues/34

@machacekondra 

This seems to work better. From what I've seen, a missing ipv4 address yields a list of lists to the json_query I replace here. Since a list of lists is not zero length, even if the nested lists are themselves zero length, this test never fails.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by mwperina** [comment]
ci add to whitelist

**Comment by cwilkers** [comment]
I've incorporated the fix from PR https://github.com/oVirt/ovirt-ansible-vm-infra/pull/35 to create the `wait_for_ip_version` var. (also addresses the original issue from issue https://github.com/oVirt/ovirt-ansible-vm-infra/issues/34)

I've also taken the liberty of swapping around the sense of the IP and hostname so the inventory key will be the `hostname` from the VM name, and the `ansible_host` will be the IP address where Ansible may find the host directly. (addresses issue https://github.com/oVirt/ovirt-ansible-vm-infra/issues/36)

@machacekondra @mwperina

**Review by machacekondra — APPROVED** [review]
THanks, looks good, can you please rebase?

**Comment by cwilkers** [comment]
@machacekondra I did a rebase last week, GH says I have no conflicts.

**Comment by machacekondra** [comment]
@cwilkers There are confilicts with https://github.com/oVirt/ovirt-ansible-vm-infra/pull/38.Github  disabled merge button because of that.

**Comment by cwilkers** [comment]
@machacekondra I merged master into the PR, is everything good to go?

**Comment by machacekondra** [comment]
Nope - see: gh

**Comment by cwilkers** [comment]
@machacekondra That's odd, I always see the last part as green, no conflicts.
I've rebased again, and it caught some more changes. Everything should be synchronized between master and the PR branch now.

**Pull request merged**
